PR for Reviewers to Comment
jessicl-ms/azure-rest-api-specs pull request #1
Opened 2023-01-06 23:32 UTC by jessicl-ms

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2023-01-07 01:10 UTC, djj0809 requested changes

2023-02-01 00:23 UTC, jessicl-ms commented on specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-05-01-preview/afdx.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.Cdn/validateSecret": {
DMed @huaiyizhu to ask, would Portal may want /ValidateSecret API for UrlSigningKey?

2023-02-01 00:24 UTC, jessicl-ms commented on specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-05-01-preview/afdx.json
> +            "type": "string"
Fixed

2023-02-01 00:24 UTC, jessicl-ms commented on specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-05-01-preview/afdx.json
> +            "description": "Created. The request has been fulfilled and a new delivery rule has been created.",
Updated

2023-02-01 00:24 UTC, jessicl-ms commented on specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-05-01-preview/examples/KeyGroups_Create.json
> +          }
The PM spec says we support 1-5 keys per keygroup.

2023-02-01 00:25 UTC, jessicl-ms commented on specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-05-01-preview/examples/Rules_Create_UrlSigningAction.json
> +              "name": "ModifyResponseHeader",
Thanks for catching that. Fixed!

2023-02-02 18:52 UTC, jessicl-ms commented on specification/cdn/resource-manager/Microsoft.Cdn/preview/2023-05-01-preview/afdx.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.Cdn/validateSecret": {
Confirmed that we shuold support ValidateSecret API for UrlSigningKey

2023-09-22 17:18 UTC, closed without merging